/*
* Generated file
*
* Generated from: yang module name: butler-service-impl yang module local name: butler-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Oct 06 22:24:42 EDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.butler_service.impl;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:config:butler-service:impl?revision=2014-11-16)butler-service", osgiRegistrationType = org.opendaylight.controller.butler.api.ButlerService.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:butler-service:impl", revision = "2014-11-16", localName = "butler-service")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:butler-service:impl", revision = "2014-11-16", name = "butler-service-impl")

public interface ButlerServiceServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
