/*
* Generated file
*
* Generated from: yang module name: cup-provider-impl yang module local name: cup-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Sep 16 21:47:50 EDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.cup_provider.impl;
public class CupProviderModuleFactory extends org.opendaylight.controller.config.yang.config.cup_provider.impl.AbstractCupProviderModuleFactory {

}
