/*
* Generated file
*
* Generated from: yang module name: butler-service-impl yang module local name: butler-service-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Oct 06 20:01:05 EDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.butler_service.impl;
public class ButlerServiceModuleFactory extends org.opendaylight.controller.config.yang.config.butler_service.impl.AbstractButlerServiceModuleFactory {

}
