/*
* Generated file
*
* Generated from: yang module name: cup-provider-impl yang module local name: cup-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Oct 05 21:40:56 EDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.cup_provider.impl;
public interface CupProviderModuleMXBean {
    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

}
